### PR TITLE
utils inside package

### LINKED ISSUE #12: add utility functions
https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis/issues/5

### PR DESCRIPTION
**Pull request by jacobvjk**
closes #12 

- gains `R/utils.R` with functions previously provided in `pacta.multi.loanbook.analysis` and `r2dii.plot`

Note:
- removes this line compared to the original implementation: https://github.com/RMI-PACTA/r2dii.plot/blob/88779f86a8dcb284e6650bd6a0f0b86903606145/R/utils.R#L267, because `lintr` identified `.column` as an unused object in this function

### CODE REVIEW

**Comment by jacobvjk** [comment]
not sure about the failing docs-check. Running document locally does not generate anything to commit.

**Comment by cjyetman** [comment]
> * also if anyone has an idea what the message on R 3.6 with windows means, I would appreciate the clarification

looks like this is a known issue https://github.com/igraph/rigraph/blob/3811bfee687f19ef8213c651d45c3efbfe2e8d13/.github/workflows/check/action.yml#L12

**Comment by cjyetman** [comment]
> * not sure about the failing docs-check. Running document locally does not generate anything to commit.

caused by Roxygen being set to 7.2.3 currently in DESCRIPTION
> Setting `RoxygenNote` to "7.3.1"

https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/blob/f81789e7b394b11d19b2cbcd8ab4e2fad9bd7793/DESCRIPTION#L30

**Comment by AlexAxthelm** [comment]
It looks like the windows issue is because installing the `igraph` package is failing. https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/actions/runs/8263622066/job/22605460577?pr=16#step:5:3471

**Comment by jacobvjk** [comment]
> It looks like the windows issue is because installing the `igraph` package is failing. https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/actions/runs/8263622066/job/22605460577?pr=16#step:5:3471

okay, given this hapens only in the R-CMD check workflow in this repository and not the one triggered rom the central actions repo, I wonder if I should just remove the ones from this repo and rely on the RMI/-PACTA/actions @AlexAxthelm ? It seems like a duplication of R CMD checks in any case

**Comment by AlexAxthelm** [comment]
I'll make a patch in the actions repo that lets you specify the matrix for testing R CMD CHECK.

in the meantime, it looks like igraph is only installed because of `networkD3`, and that's only called here:

https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/blob/d02b1f6f2f76b4cff8983d9513c9685194917260/R/plot_sankey.R#L112

**Comment by jacobvjk** [comment]
your suggested fix will help with the actions from the RMI-PACTA/actions repo, but not with the standard R-CMD checks that are failing here @AlexAxthelm. I take that the immediate solution is therefore to rely on the central actions and remove the local ones?

**Comment by jacobvjk** [comment]
@AlexAxthelm the version check seems to expect a version bump. Is that desired?

**Comment by AlexAxthelm** [comment]
> @AlexAxthelm the version check seems to expect a version bump. Is that desired?

@jacobvjk I think it's generally a good idea to bump versions as you update main, so you have something other than a git hash to distinguish between different versions.

if you want to disable that check, you can set `do-compare-versions: false` in the R.yml workflow file

**Comment by AlexAxthelm** [comment]
@jacobvjk See also #19, which brings back most of the R CMD checks that were here

**Review by AlexAxthelm — APPROVED** [review]
Now that we've sorted out the checks issues, looking at code.

LGTM.

**Pull request merged**
